config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: "registrations" }
  resources :tweets
  root "tweets#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tweets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

    private

    def sign_up_params
        
        params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
        
    end

    def account_update_params
        
        params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :current_password)
        
    end 
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all.order("created_at DESC")
    @tweet = Tweet.new

  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = current_user.tweets.build
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = current_user.tweets.build(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to root_path, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:tweet)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwittterClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
       <% if flash[:notice] %>
       <div class= "notification is-primary global-notification">
       <p class= "notice"><%= notice %> </p>
       <% end %>
       <% if flash[:alert]%>
       <div class= "notification is-danger global-notification">
       <p class = "alert"><%= alert%></p>
       <%end%>
       </div>
       <nav class = "navbar is-info">
       <div class = "navbar-brand">
       <%=  link_to root_path, class: "navbar-item" do %>
        <h1 class = "title is-5">Tweeter Clone</h1>
        <%end%>
        <div class="navbar-burger burger" data-target="navbarExample">
            <span></span>
            <span></span>
            <span></span>
          </div>
          </div>

          <div id="navbarExample" class="navbar-menu">
            <div class="navbar-end">
              <div class="navbar-item">
              <div class="field is-grouped">
                <p class="control">
                <%= link_to  "New Tweet", root_path, class: "button is-info is-inverted" %>
                </p>

                <% if user_signed_in? %>
                  <p class="control">
                <%= link_to  current_user.name, edit_user_registration_path, class: "button is-info" %>
                </p>
                <%= link_to  "Logout", destroy_user_session_path, method: :delete, class: "button is-info" %>

                <%else%>
                <p class="control">
                <%= link_to  "Sign Up", new_user_registration_path, class: "button is-info" %>
                </p>
                <p class="control">
                <%= link_to  "Sign In", new_user_session_path, class: "button is-info" %>
                </p>
                <%end%>
                </div>
              </div>
            </div>
          </div>


          </nav>
    <%= yield %>
  </body>
</html>

app/views/tweets/_feed.html.erb
<div class="column is-half">
    <% if user_signed_in? %>
    <article class="media box">
        <figure class="media-left">
          <p class="image is-64x64">
						<%= gravatar_image_tag(current_user.email, size: 64, alt: current_user.name) %>
          </p>
        </figure>
        <div class="media-content">
          <%= render "tweets/form"%>
        </div>
    </article>
    <%end%>


<% @tweets.each do |t|%>
    <div class="box">
      <article class="media">
        <div class="media-left">
          <figure class="image is-64x64">
						<%= gravatar_image_tag(t.user.email, size: 64, alt: t.user.name) %>
          </figure>
        </div>
        <div class="media-content">
            <div class="content">
         
            <strong><%= t.user.name %></strong><br />
            <small><%= t.user.username %></small><br /> 

            <p><%= t.tweet%></p>
            </div>
        <% if user_signed_in? %>
        <nav class="level">
        <div class="level-left is-mobile">
            <%= link_to t, class: "level-item" do %>
                <span class="icon"><i class="fa fa-link" aria-hidden="true"></i></span>
            <% end %>
            <%=link_to edit_tweet_path(t), class: "level-item" do%>
                 <span class="icon"><i class="fa fa-pencil" aria-hidden="true"></i></span>
            <%end%>
            <%= link_to  t, method: :delete, data: { confirm: "Are you sure you want to delete this tweet?"} do %>
                <span class="icon"><i class="fa fa-trash-o" aria-hidden="true"></i></span>

            <%end%>
        </div>
        </nav>
        <%end%>
        </div>
        </article>
    </div>
<%end%>
</div>

app/views/tweets/_form.html.erb
<%= simple_form_for(@tweet) do |f|%>
  <%= f.error_notification %>
  <div class="field">
    <div class="control">
      <%= f.input :tweet, label: "Tweet about it", input_html: { class: "textarea"}, wrapper: false, label_html: {class: "label"}, placeholder: "whats happening?", autofocus: true%>
    </div>
  </div>
  <%= f.button :submit, class: "button is-info"%>
<%end%>

app/views/tweets/_profile.html.erb
 <div class="column is-one-quarter">
	<nav class="panel">
		<p class="panel-heading">Profile</p>
		<div class="panel-block">
			<article class="media">
				<div class="media-left">
					<figure class="image is-64x64">
						<%= gravatar_image_tag(current_user.email, size: 64, alt: current_user.name) %>
					</figure>
				</div>
				<div class="media-content">
					<div class="content">
						<p>
							<strong><%= current_user.name %></strong><br />
							<small><%= current_user.username %></small>
						</p>
					</div>
				</div>
			</article>
		</div>
		<div class="panel-block">
			<div class="level is-mobile">
				<div class="level-item has-centered-text">
					<div>
						<p class="heading">Tweets</p>
					 	<p class="title is-6"><%= current_user.tweets.count %></p>
					</div>
				</div>
				<div class="level-item has-centered-text">
					<div>
						<p class="heading">Following</p>
						<p class="title is-6">123</p>
					</div>
				</div>
					<div class="level-item has-centered-text">
					<div>
						<p class="heading">Followers</p>
						<p class="title is-6">465K</p>
					</div>
				</div>
			</div>
		</div>
	</nav>
</div>

app/views/tweets/_trends.html.erb
<div class="column is-one-quarter">
    <nav class="panel">
        <p class="panel-heading"> Trends</p>
        <a class="panel-block">
            Trend 1
        </a>
        <a class="panel-block">
            Trend 2
        </a>
        <a class="panel-block">
            Trend 3
        </a>        
        <a class="panel-block">
            Trend 4
        </a>        
        <a class="panel-block">
            Trend 5
        </a>        
        <a class="panel-block">
            Trend 6
        </a>
    </nav>
</div>

app/views/tweets/_who-to-follow.html.erb
<div class="column">
    <nav class="panel">
        <p class="panel-heading">Who to follow</p>


<div class="panel-block">
    <article class="media">
        <div class="media-left">
            <figure class="image is-32x32">
                 <img src="https://bulma.io/images/placeholders/64x64.png">
            </figure>
        </div>
        <div class="media-content">
            <div class="content">
            <p>
                <strong>ChaCha</strong>
                <small>@chacha</small>
            </p>
            </div>
        </div>
    </article>
</div>

<div class="panel-block">
    <article class="media">
        <div class="media-left">
            <figure class="image is-32x32">
                 <img src="https://bulma.io/images/placeholders/64x64.png">
            </figure>
        </div>
        <div class="media-content">
            <div class="content">
            <p>
                <strong>Khash</strong>
                <small>@Khash_mirs</small>
            </p>
            </div>
        </div>
    </article>
</div>

<div class="panel-block">
    <article class="media">
        <div class="media-left">
            <figure class="image is-32x32">
                 <img src="https://bulma.io/images/placeholders/64x64.png">
            </figure>
        </div>
        <div class="media-content">
            <div class="content">
            <p>
                <strong>emerele</strong>
                <small>@emerele</small>
            </p>
            </div>
        </div>
    </article>
</div>

</nav>
</div>

app/views/tweets/edit.html.erb
<div class="section">
	<div class="container">
		<div class="columns is-centered">
			<div class="column is-half">
				<h1 class="title">Editing Tweet</h1>
				<%= render 'form', tweet: @tweet %>
			</div>
		</div>
	</div>
</div>

<nav class="navbar is-fixed-bottom">
	<div class="navbar-menu">
		<div class="navbar-item">
			<div class="field is-grouped">
				<p class="control">
					<%= link_to 'Cancel', tweets_path, class: "button is-dark" %>
				</p>
		</div>
	</div>
</nav>

app/views/tweets/index.html.erb
<section class="section">
  <div class="container">
  <div class="columns">
    <% if user_signed_in? %>
      <%= render "profile"%>
    <%else%>
      <%= render "trends"%>
    <%end%>

    <%= render "feed"%>
     <%= render  "who-to-follow" %>

  </div>
  </div>
</section>

app/views/tweets/new.html.erb
<div class="section">
	<div class="container">
		<div class="columns is-centered">
			<div class="column is-half">
				<h1 class="title">Create a new Tweeet</h1>
					<%= render 'form', tweet: @tweet %>
			</div>
		</div>
	</div>
</div>

<nav class="navbar is-fixed-bottom">
	<div class="navbar-menu">
		<div class="navbar-item">
			<div class="field is-grouped">
				<p class="control">
					<%= link_to 'Cancel', tweets_path, class: "button is-dark" %>
				</p>
		</div>
	</div>
</nav>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tweet:</strong>
  <%= @tweet.tweet %>
</p>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>